

-----------------------------------             SCRIPT CRIAÇÃO DE TABELAS/CONSTRAINTS OFICINA              ----------------------

/* DATABASE OFICINA */

CREATE DATABASE OFICINA; 

/* CRIANDO TABELAS E CONSTRAINTS */

-- TABELA CLIENTE

CREATE TABLE CLIENTE(
  idCLIENTE INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(45) NOT NULL,
  CPF CHAR(11) UNIQUE NOT NULL,
  Telefone VARCHAR(45) NOT NULL,
  Email VARCHAR(45),

CONSTRAINT PK_CLIENTES PRIMARY KEY(idCLIENTE)  -- definição da chave primária

);


-- TABELA VEÍCULO

CREATE TABLE VEICULO(
  idVEICULO INT NOT NULL AUTO_INCREMENT, -- chave primária
  Tipo_veículo VARCHAR (45),
  Marca VARCHAR (45),
  Modelo VARCHAR (45) NOT NULL,
  ConsertoRevisão ENUM ('CONSERTO', 'REVISÃO'),
  VEICULO_idCLIENTE INT NOT NULL,-- chave estrangeira

  CONSTRAINT PK_VEICULO PRIMARY KEY (idVEICULO),
  CONSTRAINT FK_VEICULO_CLIENTE FOREIGN KEY (VEICULO_idCLIENTE) REFERENCES CLIENTE (idCLIENTE)

);



-- TABELA ORDEM DE SERVÇO

CREATE TABLE ORDEM_SERVICO(
  idORDEM_SERVICO INT NOT NULL AUTO_INCREMENT, -- chave primária
  Servico_executado VARCHAR(45) NOT NULL,
  Data_emissao DATE NOT NULL,
  Pecas VARCHAR (100) NOT NULL,
  Status ENUM('ABERTA','EM ANDAMENTO','CONCLUÍDA','CANCELADA') NOT NULL,
  Data_entrega DATE NOT NULL,
  
  OS_idCLIENTE INT NOT NULL, -- chave estrangeira
  OS_idVEICULO INT NOT NULL, -- chave estrangeira

  CONSTRAINT PK_ORDEM_SERVICO PRIMARY KEY (idORDEM_SERVICO),
  CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (OS_idCLIENTE) REFERENCES CLIENTE (idCLIENTE),
  CONSTRAINT FK_OS_VEICULO FOREIGN KEY (OS_idVEICULO) REFERENCES VEICULO (idVEICULO)
);


-- TABELA PAGAMENTO

CREATE TABLE PAGAMENTO(
  idPAGAMENTO INT NOT NULL AUTO_INCREMENT,
  Valor VARCHAR(30) NOT NULL,
  Forma_pagamento ENUM('DINHEIRO','DEBITO','CREDITO','PIX'),
  Status ENUM('PAGO','ESPERANDO PAGAMENTO') NOT NULL,

  PAGAMENTO_idCLIENTE INT NOT NULL,  -- chave estrageira
  PAGAMENTO_idORDEM_SERVICO INT NOT NULL, -- chave estrangeira


  CONSTRAINT PK_PAGAMENTO PRIMARY KEY (idPAGAMENTO), -- chave primária
  CONSTRAINT FK_PAGAMENTO_CLIENTE FOREIGN KEY (PAGAMENTO_idCLIENTE) REFERENCES CLIENTE (idCLIENTE), -- chave estrageira tabela cliente
  CONSTRAINT FK_PAGAMENTO_OS FOREIGN KEY (PAGAMENTO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO (idORDEM_SERVICO) -- chave estrangeira tabela ordem serviço

);


-- TABELA MECANICOS 

CREATE TABLE MECANICOS(
  idMECANICOS INT NOT NULL AUTO_INCREMENT,
  Mecanico VARCHAR (45) NOT NULL,
  Especialidade VARCHAR (45),
  Telefone VARCHAR (45),
  Endereço VARCHAR (45),

  CONSTRAINT PK_MECANICOS PRIMARY KEY (idMECANICOS) -- chave primária
  
);


-- TABELA EQUIPE RESNPOSAVEL

CREATE TABLE EQUIPE_RESPONSAVEL(
  EQUIPE_RESPONSAVEL_id_MECANICOS INT NOT NULL,
  EQUIPE_RESPONSAVEL_id_ORDEM_SERVICO INT NOT NULL,

  CONSTRAINT FK_EQUIPE_RESPONSAVEL_MECANICOS FOREIGN KEY (EQUIPE_RESPONSAVEL_id_MECANICOS) REFERENCES MECANICOS (idMECANICOS),  -- chave estrangeira tabela mecanicos
  CONSTRAINT FK_EQUIPE_RESPONSAVEL_OS FOREIGN KEY (EQUIPE_RESPONSAVEL_id_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO (idORDEM_SERVICO)  -- chave estrangeira tabela ordem de serviço

);


-- TABELA FORNECEDOR

CREATE TABLE FORNECEDOR(
  idFORNECEDOR INT NOT NULL AUTO_INCREMENT,
  Fornecedor VARCHAR(45) NOT NULL,
  Contato VARCHAR(45),
  Endereço VARCHAR(45),

CONSTRAINT PK_FORNECEDOR PRIMARY KEY (idFORNECEDOR)

);

  -- TABELA PEÇAS UTILIZADAS

  CREATE TABLE PECAS_UTILIZADAS(
    PECAS_UTILIZADAS_id_FORNECEDOR INT NOT NULL,
    PECAS_UTILIZADAS_id_ORDEM_SERVICO INT NOT NULL,

    CONSTRAINT FK_PECAS_UTLIZADAS_FORNECEDOR FOREIGN KEY (PECAS_UTILIZADAS_id_FORNECEDOR) REFERENCES FORNECEDOR (idFORNECEDOR),
    CONSTRAINT FK_PECAS_UTLIZADAS_OS FOREIGN KEY (PECAS_UTILIZADAS_id_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO (idORDEM_SERVICO)
  
  );



